<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>LibraryManagement.Domain.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bogus" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

</Project>